### ISSUE TITLE
RareScanner does not seem to gather

### ISSUE THREAD

**Issue by Cyondil** [Ketrel/MinimapButtonFrame-Redux#9]
It seems stuck up in the minimap.  I seem to recall there being a way to force thing, but can't seem to recall the instructions..  Any thoughts?

![Screenshot 2022-11-04 124013](https://user-images.githubusercontent.com/89946331/200029289-68511524-debb-4b05-a84a-5bea1cde60c4.jpg)

**Comment by Cyondil** [comment]
Thought I had just needed to try the /MBF Add LibDBIcon10_RareScannerMinimapIcon to the commands to remove this and have it grouped, but it seems to not work.  I get the following message when I try adding it.  This name is not on the protected list when I go check either.

![Screenshot 2022-11-04 124609](https://user-images.githubusercontent.com/89946331/200030389-ddf1825c-3eeb-46b7-aba1-e565d0bb5e52.jpg)

**Comment by Ketrel** [comment]
I don't use Rare Scanner so I'm not familiar with some aspects.

Is the icon in your screenshot the icon that it puts on the minimap to indicate a rare, or is that the button to use to interact with the addon?

**Comment by Cyondil** [comment]
It's the actual button itself.

**Comment by Ketrel** [comment]
Ok, this is because they decided to call it "MinimapIcon" and not "MinimapButton".

Luckily you can override this in options.

If you to the Exceptions panel, the second option "Button Override." is what you need.  Put `LibDBIcon10_RareScannerMinimapIcon` in the "Add Button Override" box and hit "Okay" and it should immediately grab the button.

**Comment by Cyondil** [comment]
Perfect.  Thanks for the help.  I think I just read the Override function incorrectly!
